# Generated by Django 4.1.5 on 2023-01-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('knownFor', models.TextField()),
                ('bio', models.TextField()),
                ('imageURL', models.TextField()),
            ],
        ),
    ]
