# Generated by Django 4.1.4 on 2023-01-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='imageURL',
            field=models.ImageField(upload_to=''),
        ),
    ]
